[env:m5stack]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    m5stack/M5Stack@^0.4.6
    bblanchon/ArduinoJson@^7.0.0
build_flags =
    -Iinclude
    -I../include
    -I../src
    -I../src/platform/m5stack
    -DPLATFORM_M5STACK
    -std=gnu++17
    '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    '-DWIFI_PASS="${sysenv.WIFI_PASS}"'
build_src_filter =
    +<*>
